# Generated by Django 5.1.5 on 2025-03-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_file_type_file_user_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
    ]
